#!/bin/bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Validates a base image does not contain packages that tests expect to install.
#
# Usage: validate-image.sh IMAGE_NAME IMAGE_FILE

set -eu

if [ $# -ne 2 ]; then
    echo "Usage: validate-image.sh IMAGE_NAME IMAGE_FILE" >&2
    exit 1
fi

EXPECTED_GRUB_DEFAULT_AZL4_EFI='GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0 rd.shell=0"
GRUB_ENABLE_BLSCFG=true
GRUB_GFXMODE=auto
GRUB_TERMINAL_INPUT="console"
GRUB_TERMINAL_OUTPUT="gfxterm"
GRUB_TIMEOUT=0
GRUB_DEFAULT=saved'

# This image is built with imagecustomizer using 'bootloader: hard-reset'. This introduces spurious whitespace and
# injects kernel command-line arguments reflecting the current SELinux state.
EXPECTED_GRUB_DEFAULT_AZL4_LEGACY='GRUB_CMDLINE_LINUX="   security=selinux selinux=1  "
GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0 rd.shell=0 "
GRUB_ENABLE_BLSCFG=true
GRUB_GFXMODE=auto
GRUB_TERMINAL_INPUT="console"
GRUB_TERMINAL_OUTPUT="gfxterm"
GRUB_TIMEOUT=0
GRUB_DEFAULT=saved'

EXPECTED_GRUBENV_AZL4='# GRUB Environment Block
# WARNING: Do not edit this file by tools other than grub-editenv!!!
##################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################'

IMAGE_NAME="$1"
IMAGE_FILE="$2"
MISSING_SECOND_PACKAGE_NAME="unzip"
MISSING_SECOND_PACKAGE_PATH="/usr/bin/unzip"
DEFAULT_GRUB_REL_PATH=""
GRUBENV_REL_PATH=""
EXPECTED_GRUB_DEFAULT=""
EXPECTED_GRUBENV=""
ROOT_PART=2
PKG_MGR=rpm
case "$IMAGE_NAME" in
    azure-linux/core-efi-vhdx-2.0-amd64|\
    azure-linux/core-efi-vhdx-2.0-arm64|\
    azure-linux/core-efi-vhdx-3.0-amd64|\
    azure-linux/core-efi-vhdx-3.0-arm64|\
    azure-linux/core-legacy-vhd-2.0-amd64|\
    azure-linux/core-legacy-vhd-3.0-amd64)
        ;;
    azure-linux/core-efi-vhdx-4.0-amd64|\
    azure-linux/core-efi-vhdx-4.0-arm64)
        MISSING_SECOND_PACKAGE_NAME="jq"
        MISSING_SECOND_PACKAGE_PATH="/usr/bin/jq"
        DEFAULT_GRUB_REL_PATH="etc/default/grub"
        GRUBENV_REL_PATH="boot/grub2/grubenv"
        EXPECTED_GRUB_DEFAULT="$EXPECTED_GRUB_DEFAULT_AZL4_EFI"
        EXPECTED_GRUBENV="$EXPECTED_GRUBENV_AZL4"
        ;;
    azure-linux/core-legacy-vhd-4.0-amd64|\
    azure-linux/core-legacy-vhd-4.0-arm64)
        MISSING_SECOND_PACKAGE_NAME="jq"
        MISSING_SECOND_PACKAGE_PATH="/usr/bin/jq"
        DEFAULT_GRUB_REL_PATH="etc/default/grub"
        GRUBENV_REL_PATH="boot/grub2/grubenv"
        EXPECTED_GRUB_DEFAULT="$EXPECTED_GRUB_DEFAULT_AZL4_LEGACY"
        EXPECTED_GRUBENV="$EXPECTED_GRUBENV_AZL4"
        ;;
    ubuntu/azure-cloud-vhdx-22.04-amd64|\
    ubuntu/azure-cloud-vhdx-22.04-arm64|\
    ubuntu/azure-cloud-vhdx-24.04-amd64|\
    ubuntu/azure-cloud-vhdx-24.04-arm64)
        ROOT_PART=1
        PKG_MGR=dpkg
        ;;
    *)
        echo "ERROR: unrecognized image: '$IMAGE_NAME'" >&2
        exit 1
        ;;
esac

if [ ! -f "$IMAGE_FILE" ]; then
    echo "ERROR: file not found: $IMAGE_FILE" >&2
    exit 1
fi

RAW="$(mktemp --suffix=.raw)"
MNT="$(mktemp -d)"

cleanup() {
    if mountpoint -q "$MNT" 2>/dev/null; then
        umount "$MNT" || true
    fi
    rmdir "$MNT" 2>/dev/null || true

    if [ -n "${LOOP:-}" ]; then
        losetup -d "$LOOP" 2>/dev/null || true
    fi

    rm -f "$RAW"
}
trap cleanup EXIT

qemu-img convert -O raw "$IMAGE_FILE" "$RAW"
LOOP="$(losetup --show -f -P "$RAW")"
mount -o ro "${LOOP}p${ROOT_PART}" "$MNT"

is_installed() {
    if [ "$PKG_MGR" = "dpkg" ]; then
        local status
        status="$(chroot "$MNT" dpkg-query -W -f='${Status}' "$1" 2>/dev/null)" || return 1
        if [ "$status" = "install ok installed" ]; then
            return 0
        fi
        return 1
    else
        chroot "$MNT" rpm -q "$1" >/dev/null 2>&1
    fi
}

is_present() {
    chroot "$MNT" test -e "$1"
}

FAILED=0
for pkg in tree $MISSING_SECOND_PACKAGE_NAME; do
    if is_installed "$pkg"; then
        echo "FAIL: '$pkg' is pre-installed in $IMAGE_NAME" >&2
        FAILED=1
    else
        echo "OK:   '$pkg' absent"
    fi
done

for path in /usr/bin/tree $MISSING_SECOND_PACKAGE_PATH; do
    if is_present "$path"; then
        echo "FAIL: '$path' is present in $IMAGE_NAME" >&2
        FAILED=1
    else
        echo "OK:   '$path' absent"
    fi
done

for pkg in chrony curl; do
    if is_installed "$pkg"; then
        echo "OK:   '$pkg' present"
    else
        echo "FAIL: '$pkg' is not pre-installed in $IMAGE_NAME" >&2
        FAILED=1
    fi

done

for path in /usr/sbin/chronyd /usr/bin/curl; do
    if is_present "$path"; then
        echo "OK:   '$path' present"
    else
        echo "FAIL: '$path' is not present in $IMAGE_NAME" >&2
        FAILED=1
    fi
done

# Verify that kernel command line args used by tests are not already present.
# Tests add these via extraCommandLine and assert they appear together.
# If the base image already ships them the assertions are meaningless.
# Fail only if BOTH console=tty0 and console=ttyS0 are already set.
# Having one absent is sufficient for the test assertions to be meaningful.
console_tty0_present=false
console_ttyS0_present=false
for file in "$MNT/etc/default/grub" "$MNT/etc/kernel/cmdline"; do
    if [ -f "$file" ]; then
        grep -q 'console=tty0' "$file" && console_tty0_present=true
        grep -q 'console=ttyS0' "$file" && console_ttyS0_present=true
    fi
done

if $console_tty0_present && $console_ttyS0_present; then
    echo "FAIL: both 'console=tty0' and 'console=ttyS0' already set in $IMAGE_NAME" >&2
    FAILED=1
else
    echo "OK:   at least one of console=tty0, console=ttyS0 absent from $IMAGE_NAME"
fi

# Assert that AZL4 base images ship the exact grub configuration that we expect.
# We overwrite these files using a bundled template that assumes a specific starting state.
ensure_file_contents() {
    local rel_path="$1"
    local expected_content="$2"

    if [[ -n "$rel_path" ]]; then
        abs_path="$MNT/$rel_path"
        if [ ! -f "$abs_path" ]; then
            echo "FAIL: $abs_path is missing" >&2
            FAILED=1
        else
            local actual_content="$(cat "$abs_path")"
            if [ "$actual_content" = "$expected_content" ]; then
                echo "OK:   $abs_path matches the expected content"
            else
                echo "FAIL: $abs_path does not match expected content" >&2
                echo "----- expected -----" >&2
                printf '%s\n' "$expected_content" >&2
                echo "----- actual -----" >&2
                printf '%s\n' "$actual_content" >&2
                echo "----- diff (expected vs actual) -----" >&2
                diff -u <(printf '%s\n' "$expected_content") <(printf '%s\n' "$actual_content") >&2 || true
                FAILED=1
            fi
        fi
    fi
}
ensure_file_contents "$DEFAULT_GRUB_REL_PATH" "$EXPECTED_GRUB_DEFAULT"
ensure_file_contents "$GRUBENV_REL_PATH" "$EXPECTED_GRUBENV"

exit $FAILED
